In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
print('Libraries imported.')

Libraries imported.

In [18]:
url = '/content/bmw.csv'
desired_columns = ['model','year','price','transmission','fuelType','tax','mpg','engineSize']
# Load the data, letting pandas infer the header. This corrects the initial data loading issue.
df = pd.read_csv(url)
# Filter the DataFrame to keep only the desired columns.
# This handles cases where the CSV might contain additional columns (like 'mileage') not in our desired list.
df = df[desired_columns]
df.head()

       model  year  price transmission fuelType  tax   mpg  engineSize
0   5 Series  2014  11200    Automatic   Diesel  125  57.6         2.0
1   6 Series  2018  27000    Automatic   Petrol  145  42.8         2.0
2   5 Series  2016  16000    Automatic   Diesel  160  51.4         3.0
3   1 Series  2017  12750    Automatic   Diesel  145  72.4         1.5
4   7 Series  2014  14500    Automatic   Diesel  160  50.4         3.0

In [4]:
print('Shape:', df.shape)
print('\nColumn Names:', df.columns.tolist())
df.head()

Shape: (999, 8)

Column Names: ['model', 'year', 'price', 'transmission', 'fuelType', 'tax', 'mpg', 'engineSize']

,model,year,price,transmission,fuelType,tax,mpg,engineSize
model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2
6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2
5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3
1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, model to  3 Series
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         999 non-null    object
 1   year          999 non-null    object
 2   price         999 non-null    object
 3   transmission  999 non-null    object
 4   fuelType      999 non-null    object
 5   tax           999 non-null    object
 6   mpg           999 non-null    object
 7   engineSize    999 non-null    object
dtypes: object(8)
memory usage: 102.5+ KB

In [6]:
df.describe()

       model   year      price transmission fuelType  tax   mpg engineSize
count    999    999        999          999      999  999   999        999
unique     9    433          4          949        5   18    67          8
top     2019  18998  Semi-Auto         5000   Diesel  145  65.7          2
freq     251     20        593            8      709  477    77        595

In [7]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [13]:
for col in df.select_dtypes(include=['float64','int64']).columns:
    df[col] = df[col].fillna(df[col].mean())


for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

model           0
year            0
price           0
transmission    0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [9]:
before = df.shape[0]
df.drop_duplicates(inplace=True)
after = df.shape[0]
print('Duplicates removed:', before - after)

Duplicates removed: 4

In [24]:
encoder = LabelEncoder()
df['model'] = encoder.fit_transform(df['model'])
df.head()

   model  year  price transmission fuelType  tax   mpg  engineSize
0      4  2014  11200    Automatic   Diesel  125  57.6         2.0
1      5  2018  27000    Automatic   Petrol  145  42.8         2.0
2      4  2016  16000    Automatic   Diesel  160  51.4         3.0
3      0  2017  12750    Automatic   Diesel  145  72.4         1.5
4      6  2014  14500    Automatic   Diesel  160  50.4         3.0

In [29]:
scaler = StandardScaler()
desired_columns = ['model','year','price','transmission','fuelType','tax','mpg','engineSize']
df.head()

,model,year,price,transmission,fuelType,tax,mpg,engineSize
0,-0.144155,-1.784591,-1.000624,-1.857538,-0.625000,-0.094092,0.004342,-0.332249
1,0.041479,0.549645,0.479285,-1.857538,1.645934,0.268821,-0.479268,-0.332249
2,-0.144155,-0.617473,-0.551031,-1.857538,-0.625000,0.541006,-0.198252,1.495668
3,-0.886690,-0.033914,-0.855443,-1.857538,-0.625000,0.268821,0.487952,-1.246207
4,0.227113,-1.784591,-0.691529,-1.857538,-0.625000,0.541006,-0.230928,1.495668

In [26]:
df.to_csv('assignment2_cleaned_iris.csv', index=False)
print('Saved: assignment2_cleaned_iris.csv')

Saved: assignment2_cleaned_iris.csv

Conclusion:
This data preprocessing pipeline successfully cleaned and prepared the BMW dataset for analysis and modeling. Missing values were handled, duplicate records were removed, and categorical features like model were encoded numerically. The dataset is now structured, consistent, and saved in a clean format, making it suitable for further statistical analysis or machine learning tasks.